### ISSUE TITLE
Error on build.gradle when adding the plugin

### ISSUE THREAD

**Issue by sergiomarquesmoura** [uPhyca/gradle-android-aspectj-plugin#22]
Hello,

I am getting the following error when I try to sync my build.grade after editing it as you have on the README.md file

Error:(16, 0) Could not find matching constructor for: org.gradle.api.GradleException(org.gradle.api.GradleException)

Just for me to be clear, I don't need to add any folder to my project right? Since grade automatically downloads all the required libraries when I specify the classpath in dependencies and I write the apply plugin: 'android-aspectj' on build.grade.

Thanks in advance

**Comment by esmasui** [comment]
Hello,
Could you please send me the stack trace.
Thanks,

**Comment by nsiitk** [comment]
I am also facing the same issue. Its due to GradleException constructor on line 28. it should be 
public GradleException(String message,
               Throwable cause) 
the string message part is missing.


Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.GradleException(org.gradle.api.GradleException)
	at com.uphyca.gradle.android.AndroidAspectJPlugin.apply(AndroidAspectJPlugin.groovy:28)
	at com.uphyca.gradle.android.AndroidAspectJPlugin.apply(AndroidAspectJPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
