### ISSUE TITLE
Build fail with java7

### ISSUE THREAD

**Issue by esmasui** [uPhyca/gradle-android-aspectj-plugin#36]
```
$ ./gradlew -version
------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Mac OS X 10.10.5 x86_64
```

```
$ ./gradlew --full-stacktrace clean build install
:buildSrc:plugin:compileJava UP-TO-DATE
:buildSrc:plugin:compileGroovy
:buildSrc:plugin:processResources
:buildSrc:plugin:classes
:buildSrc:plugin:jar
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:buildSrc:plugin:groovydoc
:buildSrc:plugin:javadocJar
:buildSrc:plugin:sourcesJar
:buildSrc:plugin:signArchives
:buildSrc:plugin:assemble
:buildSrc:plugin:compileTestJava UP-TO-DATE
:buildSrc:plugin:compileTestGroovy
:buildSrc:plugin:processTestResources UP-TO-DATE
:buildSrc:plugin:testClasses
:buildSrc:plugin:test
:buildSrc:plugin:check
:buildSrc:plugin:build
:clean
:androidAptIntegration:clean
:annotationBasedStyle:clean
:codeBasedStyle:clean
:declareMixin:clean
:declareParents:clean UP-TO-DATE
:plugin:clean
:assemble UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE
:androidAptIntegration:preBuild UP-TO-DATE
:androidAptIntegration:preDebugBuild UP-TO-DATE
:androidAptIntegration:checkDebugManifest
:androidAptIntegration:preReleaseBuild UP-TO-DATE
:androidAptIntegration:prepareComAndroidSupportAppcompatV72301Library
:androidAptIntegration:prepareComAndroidSupportSupportV42301Library
:androidAptIntegration:prepareDebugDependencies
:androidAptIntegration:compileDebugAidl
:androidAptIntegration:compileDebugRenderscript
:androidAptIntegration:generateDebugBuildConfig
:androidAptIntegration:generateDebugAssets UP-TO-DATE
:androidAptIntegration:mergeDebugAssets
:androidAptIntegration:generateDebugResValues UP-TO-DATE
:androidAptIntegration:generateDebugResources
:androidAptIntegration:mergeDebugResources
:androidAptIntegration:processDebugManifest
:androidAptIntegration:processDebugResources
:androidAptIntegration:generateDebugSources
:androidAptIntegration:processDebugJavaRes UP-TO-DATE
:androidAptIntegration:compileDebugJava
Note: /Users/masui/Projects/gradle-android-aspectj-plugin/tests/androidAptIntegration/build/generated/source/apt/debug/com/uphyca/gradle/android/aspectj/DaggerMyComponent.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:androidAptIntegration:compileDebugAspectj
:androidAptIntegration:compileDebugNdk UP-TO-DATE
:androidAptIntegration:compileDebugSources
:androidAptIntegration:preDexDebug
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.aspectj.runtime.internal.cflowstack.ThreadStackFactoryImpl$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

:androidAptIntegration:dexDebug
:androidAptIntegration:validateDebugSigning
:androidAptIntegration:packageDebug
:androidAptIntegration:zipalignDebug
:androidAptIntegration:assembleDebug
:androidAptIntegration:checkReleaseManifest
:androidAptIntegration:prepareReleaseDependencies
:androidAptIntegration:compileReleaseAidl
:androidAptIntegration:compileReleaseRenderscript
:androidAptIntegration:generateReleaseBuildConfig
:androidAptIntegration:generateReleaseAssets UP-TO-DATE
:androidAptIntegration:mergeReleaseAssets
:androidAptIntegration:generateReleaseResValues UP-TO-DATE
:androidAptIntegration:generateReleaseResources
:androidAptIntegration:mergeReleaseResources
:androidAptIntegration:processReleaseManifest
:androidAptIntegration:processReleaseResources
:androidAptIntegration:generateReleaseSources
:androidAptIntegration:processReleaseJavaRes UP-TO-DATE
:androidAptIntegration:compileReleaseJava
Note: /Users/masui/Projects/gradle-android-aspectj-plugin/tests/androidAptIntegration/build/generated/source/apt/release/com/uphyca/gradle/android/aspectj/DaggerMyComponent.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:androidAptIntegration:compileReleaseAspectj
:androidAptIntegration:compileReleaseNdk UP-TO-DATE
:androidAptIntegration:compileReleaseSources
:androidAptIntegration:lintVitalRelease SKIPPED
:androidAptIntegration:preDexRelease
:androidAptIntegration:dexRelease
:androidAptIntegration:packageRelease
:androidAptIntegration:assembleRelease
:androidAptIntegration:assemble
:androidAptIntegration:compileLint
:androidAptIntegration:lint
Ran lint on variant release: 3 issues found
Ran lint on variant debug: 3 issues found
Wrote HTML report to file:/Users/masui/Projects/gradle-android-aspectj-plugin/tests/androidAptIntegration/build/outputs/lint-results.html
Wrote XML report to /Users/masui/Projects/gradle-android-aspectj-plugin/tests/androidAptIntegration/build/outputs/lint-results.xml
:androidAptIntegration:preCompileDebugUnitTestJava
:androidAptIntegration:preDebugUnitTestBuild UP-TO-DATE
:androidAptIntegration:prepareDebugUnitTestDependencies
:androidAptIntegration:processDebugUnitTestJavaRes UP-TO-DATE
:androidAptIntegration:compileDebugUnitTestJava UP-TO-DATE
:androidAptIntegration:compileDebugUnitTestSources UP-TO-DATE
:androidAptIntegration:mockableAndroidJar
:androidAptIntegration:assembleDebugUnitTest
:androidAptIntegration:testDebug
:androidAptIntegration:preCompileReleaseUnitTestJava
:androidAptIntegration:preReleaseUnitTestBuild UP-TO-DATE
:androidAptIntegration:prepareReleaseUnitTestDependencies
:androidAptIntegration:processReleaseUnitTestJavaRes UP-TO-DATE
:androidAptIntegration:compileReleaseUnitTestJava UP-TO-DATE
:androidAptIntegration:compileReleaseUnitTestSources UP-TO-DATE
:androidAptIntegration:assembleReleaseUnitTest
:androidAptIntegration:testRelease
:androidAptIntegration:test
:androidAptIntegration:check
:androidAptIntegration:build
:annotationBasedStyle:preBuild UP-TO-DATE
:annotationBasedStyle:preDebugBuild UP-TO-DATE
:annotationBasedStyle:checkDebugManifest
:annotationBasedStyle:preReleaseBuild UP-TO-DATE
:annotationBasedStyle:prepareComAndroidSupportAppcompatV72301Library
:annotationBasedStyle:prepareComAndroidSupportSupportV42301Library
:annotationBasedStyle:prepareDebugDependencies
:annotationBasedStyle:compileDebugAidl
:annotationBasedStyle:compileDebugRenderscript
:annotationBasedStyle:generateDebugBuildConfig
:annotationBasedStyle:generateDebugAssets UP-TO-DATE
:annotationBasedStyle:mergeDebugAssets
:annotationBasedStyle:generateDebugResValues UP-TO-DATE
:annotationBasedStyle:generateDebugResources
:annotationBasedStyle:mergeDebugResources
:annotationBasedStyle:processDebugManifest
:annotationBasedStyle:processDebugResources
:annotationBasedStyle:generateDebugSources
:annotationBasedStyle:processDebugJavaRes UP-TO-DATE
:annotationBasedStyle:compileDebugJava
:annotationBasedStyle:compileDebugAspectj
:annotationBasedStyle:compileDebugNdk UP-TO-DATE
:annotationBasedStyle:compileDebugSources
:annotationBasedStyle:preDexDebug
:annotationBasedStyle:dexDebug
:annotationBasedStyle:validateDebugSigning
:annotationBasedStyle:packageDebug
:annotationBasedStyle:zipalignDebug
:annotationBasedStyle:assembleDebug
:annotationBasedStyle:checkReleaseManifest
:annotationBasedStyle:prepareReleaseDependencies
:annotationBasedStyle:compileReleaseAidl
:annotationBasedStyle:compileReleaseRenderscript
:annotationBasedStyle:generateReleaseBuildConfig
:annotationBasedStyle:generateReleaseAssets UP-TO-DATE
:annotationBasedStyle:mergeReleaseAssets
:annotationBasedStyle:generateReleaseResValues UP-TO-DATE
:annotationBasedStyle:generateReleaseResources
:annotationBasedStyle:mergeReleaseResources
:annotationBasedStyle:processReleaseManifest
:annotationBasedStyle:processReleaseResources
:annotationBasedStyle:generateReleaseSources
:annotationBasedStyle:processReleaseJavaRes UP-TO-DATE
:annotationBasedStyle:compileReleaseJava
:annotationBasedStyle:compileReleaseAspectj
:annotationBasedStyle:compileReleaseNdk UP-TO-DATE
:annotationBasedStyle:compileReleaseSources
:annotationBasedStyle:lintVitalRelease SKIPPED
:annotationBasedStyle:preDexRelease
:annotationBasedStyle:dexRelease
:annotationBasedStyle:packageRelease
:annotationBasedStyle:assembleRelease
:annotationBasedStyle:assemble
:annotationBasedStyle:compileLint
:annotationBasedStyle:lint
Ran lint on variant debug: 1 issues found
Ran lint on variant release: 1 issues found
Wrote HTML report to file:/Users/masui/Projects/gradle-android-aspectj-plugin/tests/annotationBasedStyle/build/outputs/lint-results.html
Wrote XML report to /Users/masui/Projects/gradle-android-aspectj-plugin/tests/annotationBasedStyle/build/outputs/lint-results.xml
:annotationBasedStyle:preCompileDebugUnitTestJava
:annotationBasedStyle:preDebugUnitTestBuild UP-TO-DATE
:annotationBasedStyle:prepareDebugUnitTestDependencies
:annotationBasedStyle:processDebugUnitTestJavaRes UP-TO-DATE
:annotationBasedStyle:compileDebugUnitTestJava
:annotationBasedStyle:compileDebugUnitTestSources
:annotationBasedStyle:mockableAndroidJar
:annotationBasedStyle:assembleDebugUnitTest
:annotationBasedStyle:testDebug
:annotationBasedStyle:preCompileReleaseUnitTestJava
:annotationBasedStyle:preReleaseUnitTestBuild UP-TO-DATE
:annotationBasedStyle:prepareReleaseUnitTestDependencies
:annotationBasedStyle:processReleaseUnitTestJavaRes UP-TO-DATE
:annotationBasedStyle:compileReleaseUnitTestJava
:annotationBasedStyle:compileReleaseUnitTestSources
:annotationBasedStyle:assembleReleaseUnitTest
:annotationBasedStyle:testRelease
:annotationBasedStyle:test
:annotationBasedStyle:check
:annotationBasedStyle:build
:codeBasedStyle:preBuild UP-TO-DATE
:codeBasedStyle:preDebugBuild UP-TO-DATE
:codeBasedStyle:checkDebugManifest
:codeBasedStyle:preReleaseBuild UP-TO-DATE
:codeBasedStyle:prepareComAndroidSupportAppcompatV72301Library
:codeBasedStyle:prepareComAndroidSupportSupportV42301Library
:codeBasedStyle:prepareDebugDependencies
:codeBasedStyle:compileDebugAidl
:codeBasedStyle:compileDebugRenderscript
:codeBasedStyle:generateDebugBuildConfig
:codeBasedStyle:generateDebugAssets UP-TO-DATE
:codeBasedStyle:mergeDebugAssets
:codeBasedStyle:generateDebugResValues UP-TO-DATE
:codeBasedStyle:generateDebugResources
:codeBasedStyle:mergeDebugResources
:codeBasedStyle:processDebugManifest
:codeBasedStyle:processDebugResources
:codeBasedStyle:generateDebugSources
:codeBasedStyle:processDebugJavaRes UP-TO-DATE
:codeBasedStyle:compileDebugJava
:codeBasedStyle:compileDebugAspectj
:codeBasedStyle:compileDebugNdk UP-TO-DATE
:codeBasedStyle:compileDebugSources
:codeBasedStyle:preDexDebug
:codeBasedStyle:dexDebug
:codeBasedStyle:validateDebugSigning
:codeBasedStyle:packageDebug
:codeBasedStyle:zipalignDebug
:codeBasedStyle:assembleDebug
:codeBasedStyle:checkReleaseManifest
:codeBasedStyle:prepareReleaseDependencies
:codeBasedStyle:compileReleaseAidl
:codeBasedStyle:compileReleaseRenderscript
:codeBasedStyle:generateReleaseBuildConfig
:codeBasedStyle:generateReleaseAssets UP-TO-DATE
:codeBasedStyle:mergeReleaseAssets
:codeBasedStyle:generateReleaseResValues UP-TO-DATE
:codeBasedStyle:generateReleaseResources
:codeBasedStyle:mergeReleaseResources
:codeBasedStyle:processReleaseManifest
:codeBasedStyle:processReleaseResources
:codeBasedStyle:generateReleaseSources
:codeBasedStyle:processReleaseJavaRes UP-TO-DATE
:codeBasedStyle:compileReleaseJava
:codeBasedStyle:compileReleaseAspectj
:codeBasedStyle:compileReleaseNdk UP-TO-DATE
:codeBasedStyle:compileReleaseSources
:codeBasedStyle:lintVitalRelease SKIPPED
:codeBasedStyle:preDexRelease
:codeBasedStyle:dexRelease
:codeBasedStyle:packageRelease
:codeBasedStyle:assembleRelease
:codeBasedStyle:assemble
:codeBasedStyle:compileLint
:codeBasedStyle:lint
Ran lint on variant release: 1 issues found
Ran lint on variant debug: 1 issues found
Wrote HTML report to file:/Users/masui/Projects/gradle-android-aspectj-plugin/tests/codeBasedStyle/build/outputs/lint-results.html
Wrote XML report to /Users/masui/Projects/gradle-android-aspectj-plugin/tests/codeBasedStyle/build/outputs/lint-results.xml
:codeBasedStyle:preCompileDebugUnitTestJava
:codeBasedStyle:preDebugUnitTestBuild UP-TO-DATE
:codeBasedStyle:prepareDebugUnitTestDependencies
:codeBasedStyle:processDebugUnitTestJavaRes UP-TO-DATE
:codeBasedStyle:compileDebugUnitTestJava
:codeBasedStyle:compileDebugUnitTestSources
:codeBasedStyle:mockableAndroidJar
:codeBasedStyle:assembleDebugUnitTest
:codeBasedStyle:testDebug
:codeBasedStyle:preCompileReleaseUnitTestJava
:codeBasedStyle:preReleaseUnitTestBuild UP-TO-DATE
:codeBasedStyle:prepareReleaseUnitTestDependencies
:codeBasedStyle:processReleaseUnitTestJavaRes UP-TO-DATE
:codeBasedStyle:compileReleaseUnitTestJava
:codeBasedStyle:compileReleaseUnitTestSources
:codeBasedStyle:assembleReleaseUnitTest
:codeBasedStyle:testRelease
:codeBasedStyle:test
:codeBasedStyle:check
:codeBasedStyle:build
:declareMixin:preBuild UP-TO-DATE
:declareMixin:preDebugBuild UP-TO-DATE
:declareMixin:checkDebugManifest
:declareMixin:preReleaseBuild UP-TO-DATE
:declareMixin:prepareComAndroidSupportAppcompatV72301Library
:declareMixin:prepareComAndroidSupportSupportV42301Library
:declareMixin:prepareDebugDependencies
:declareMixin:compileDebugAidl
:declareMixin:compileDebugRenderscript
:declareMixin:generateDebugBuildConfig
:declareMixin:generateDebugAssets UP-TO-DATE
:declareMixin:mergeDebugAssets
:declareMixin:generateDebugResValues UP-TO-DATE
:declareMixin:generateDebugResources
:declareMixin:mergeDebugResources
:declareMixin:processDebugManifest
:declareMixin:processDebugResources
:declareMixin:generateDebugSources
:declareMixin:processDebugJavaRes UP-TO-DATE
:declareMixin:compileDebugJava
:declareMixin:compileDebugAspectj
enum type com.uphyca.gradle.android.aspectj.Mood matches a declare parents type pattern but is being ignored [Xlint:enumAsTargetForDecpIgnored]
:declareMixin:compileDebugNdk UP-TO-DATE
:declareMixin:compileDebugSources
:declareMixin:preDexDebug
:declareMixin:dexDebug
:declareMixin:validateDebugSigning
:declareMixin:packageDebug
:declareMixin:zipalignDebug
:declareMixin:assembleDebug
:declareMixin:checkReleaseManifest
:declareMixin:prepareReleaseDependencies
:declareMixin:compileReleaseAidl
:declareMixin:compileReleaseRenderscript
:declareMixin:generateReleaseBuildConfig
:declareMixin:generateReleaseAssets UP-TO-DATE
:declareMixin:mergeReleaseAssets
:declareMixin:generateReleaseResValues UP-TO-DATE
:declareMixin:generateReleaseResources
:declareMixin:mergeReleaseResources
:declareMixin:processReleaseManifest
:declareMixin:processReleaseResources
:declareMixin:generateReleaseSources
:declareMixin:processReleaseJavaRes UP-TO-DATE
:declareMixin:compileReleaseJava
:declareMixin:compileReleaseAspectj
enum type com.uphyca.gradle.android.aspectj.Mood matches a declare parents type pattern but is being ignored [Xlint:enumAsTargetForDecpIgnored]
:declareMixin:compileReleaseNdk UP-TO-DATE
:declareMixin:compileReleaseSources
:declareMixin:lintVitalRelease SKIPPED
:declareMixin:preDexRelease
:declareMixin:dexRelease
:declareMixin:packageRelease
:declareMixin:assembleRelease
:declareMixin:assemble
:declareMixin:compileLint
:declareMixin:lint
Ran lint on variant release: 1 issues found
Ran lint on variant debug: 1 issues found
Wrote HTML report to file:/Users/masui/Projects/gradle-android-aspectj-plugin/tests/declareMixin/build/outputs/lint-results.html
Wrote XML report to /Users/masui/Projects/gradle-android-aspectj-plugin/tests/declareMixin/build/outputs/lint-results.xml
:declareMixin:preCompileDebugUnitTestJava
:declareMixin:preDebugUnitTestBuild UP-TO-DATE
:declareMixin:prepareDebugUnitTestDependencies
:declareMixin:processDebugUnitTestJavaRes UP-TO-DATE
:declareMixin:compileDebugUnitTestJava
:declareMixin:compileDebugUnitTestSources
:declareMixin:mockableAndroidJar
:declareMixin:assembleDebugUnitTest
:declareMixin:testDebug
:declareMixin:preCompileReleaseUnitTestJava
:declareMixin:preReleaseUnitTestBuild UP-TO-DATE
:declareMixin:prepareReleaseUnitTestDependencies
:declareMixin:processReleaseUnitTestJavaRes UP-TO-DATE
:declareMixin:compileReleaseUnitTestJava
:declareMixin:compileReleaseUnitTestSources
:declareMixin:assembleReleaseUnitTest
:declareMixin:testRelease
:declareMixin:test
:declareMixin:check
:declareMixin:build
:declareParents:preBuild UP-TO-DATE
:declareParents:preDebugBuild UP-TO-DATE
:declareParents:checkDebugManifest
:declareParents:preReleaseBuild UP-TO-DATE
:declareParents:prepareComAndroidSupportAppcompatV72301Library
:declareParents:prepareComAndroidSupportSupportV42301Library
:declareParents:prepareDebugDependencies
:declareParents:compileDebugAidl
:declareParents:compileDebugRenderscript
:declareParents:generateDebugBuildConfig
:declareParents:generateDebugAssets UP-TO-DATE
:declareParents:mergeDebugAssets
:declareParents:generateDebugResValues UP-TO-DATE
:declareParents:generateDebugResources
:declareParents:mergeDebugResources
:declareParents:processDebugManifest
:declareParents:processDebugResources
:declareParents:generateDebugSources
:declareParents:processDebugJavaRes UP-TO-DATE
:declareParents:compileDebugJava
:declareParents:compileDebugAspectj
The type android.support.v4.widget.DrawerLayoutImpl cannot be resolved. It is indirectly referenced from required .class files
:declareParents:compileDebugAspectj FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':declareParents:compileDebugAspectj'.
> The type android.support.v4.widget.DrawerLayoutImpl cannot be resolved. It is indirectly referenced from required .class files

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':declareParents:compileDebugAspectj'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:155)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:152)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:100)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:94)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:94)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.GradleException: The type android.support.v4.widget.DrawerLayoutImpl cannot be resolved. It is indirectly referenced from required .class files
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
	at com.uphyca.gradle.android.AspectjCompile.compile(AspectjCompile.groovy:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more


BUILD FAILED

Total time: 2 mins 44.377 secs
```

**Comment by esmasui** [comment]
Couldn't reproduce...
